# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: ci integration test

on:
  push:
    branches: [ "ci-integration-test" ]
  pull_request:
    branches: [ "ci-integration-test" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.1.2]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
     - uses: actions/checkout@v2
     - name: Use Node.js
       uses: actions/setup-node@v2
       with: 
        node-version: "14.x"

     - name: Install dependencies
       run: npm install


     - name: Run test
       env: 
        NODE_ENV: 'production'
        MONGO_USER: ${{ secrets.MONGO_USER }}
        MONGO_PASSWORD:  ${{ secrets.MONGO_PASSWORD }}
       run: npm test
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "movies-app-api"
          heroku_email: "delatorreoscar81@gmail.com"